### ISSUE TITLE
May want to provide a warning for those who use postLayout in TableViewRow/ListViewRow

### ISSUE THREAD

**Issue by Arialle** [FokkeZB/nl.fokkezb.infiniteScroll#51]
I am not even sure why I am making this issue since it's not the module's fault. However, for anyone who wants to use this module with Alloy Collections, whenever you perform a fetch to add data onto a collection, the entire containing view (ListView, TableView) and rows will get redrawn/recreated.

My use case was that each of my TableViewRow(s) have an ImageView in them; those ImageViews have a postLayout event to figure out whether or not to fetch a newer image blob from the server. I noticed that my server was receiving requests for the rows that were already drawn. I haven't tried, but I am thinking about simplifying the TableViewRow(s) further.

**Comment by FokkeZB** [comment]
Thanks @Arialle 

That's why in the README I'm using:

```
     // don't reset the collection, but add to it
        add: true,
```

This will add the new models and note replace them.

But yes, Alloy will still redraw the full ListView. I recently created a ticket to discuss how we can improve that. Please watch it and leave any suggestions there:

https://jira.appcelerator.org/browse/ALOY-1328
